apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-5a8a"
    labels:
        app: "myakscluster-5a8a"
spec:
    type: LoadBalancer
    ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
    selector:
        app: "myakscluster-5a8a"